"""Add read_at, is_recovered, and recovered_at to Alert model

Revision ID: 88c69691a46d
Revises: c6fb6d3e87cd
Create Date: 2025-03-21 17:14:40.927883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88c69691a46d'
down_revision = 'c6fb6d3e87cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_recovered', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recovered_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('terminals', schema=None) as batch_op:
        batch_op.drop_column('user_agent')
        batch_op.drop_column('upstream_traffic')
        batch_op.drop_column('total_traffic')
        batch_op.drop_column('downstream_traffic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terminals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downstream_traffic', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_traffic', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('upstream_traffic', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_agent', mysql.VARCHAR(length=256), nullable=True))

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('recovered_at')
        batch_op.drop_column('is_recovered')
        batch_op.drop_column('read_at')

    # ### end Alembic commands ###
