"""添加location字段到Terminal模型

Revision ID: b81d1c06966f
Revises: 
Create Date: 2025-03-18 21:01:12.473457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b81d1c06966f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terminals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connected_device_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('port_number', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('vlan_id', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('connection_type', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('in_traffic', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('out_traffic', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('bandwidth_usage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('hostname',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('ip_address',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('mac_address',
               existing_type=mysql.VARCHAR(length=17),
               nullable=False)
        batch_op.drop_index('ix_terminals_ip_address')
        batch_op.create_unique_constraint(None, ['ip_address'])
        batch_op.create_foreign_key(None, 'devices', ['connected_device_id'], ['id'])
        batch_op.drop_column('user_agent')
        batch_op.drop_column('downstream_traffic')
        batch_op.drop_column('upstream_traffic')
        batch_op.drop_column('total_traffic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terminals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_traffic', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('upstream_traffic', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('downstream_traffic', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_agent', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_terminals_ip_address', ['ip_address'], unique=False)
        batch_op.alter_column('mac_address',
               existing_type=mysql.VARCHAR(length=17),
               nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('hostname',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('bandwidth_usage')
        batch_op.drop_column('out_traffic')
        batch_op.drop_column('in_traffic')
        batch_op.drop_column('connection_type')
        batch_op.drop_column('vlan_id')
        batch_op.drop_column('port_number')
        batch_op.drop_column('connected_device_id')

    # ### end Alembic commands ###
