"""添加location字段到Terminal模型

Revision ID: c6fb6d3e87cd
Revises: b81d1c06966f
Create Date: 2025-03-18 21:11:08.669022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6fb6d3e87cd'
down_revision = 'b81d1c06966f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terminals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terminals', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
