"""修改User模型：移除UserMixin继承，新增phone_number和notification_preferences字段

Revision ID: e21d4b8dce9d
Revises: 88c69691a46d
Create Date: 2025-04-10 22:15:39.898412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21d4b8dce9d'
down_revision = '88c69691a46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('notification_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_preferences')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
